### ISSUE TITLE
Home link on breadcrumbs not working

### ISSUE THREAD

**Issue by robwoodford** [robwoodford/SEC-Card-Game-staging#1]
The link when clicking Home on the breadcrumbs doesn't go back to the main home page. This may be an issue only because we haven't assigned the domain yet, but just checking that when we do this will resolve relative to that.

**Comment by JeanCarletta** [comment]
This is also now broken in my repo, suggesting it's a change in the Github setup, not anything we did.  Not sure how to fix but once we know what URL we want we can hardwire in _includes/breadcrumbs.html if it doesn't work on the host system.  I will mark the correct spot in the file.

**Comment by robwoodford** [comment]
This is now resolved.
