### ISSUE TITLE
revert smart meter card to old text

### ISSUE THREAD

**Issue by JeanCarletta** [robwoodford/SEC-Card-Game-staging#13]
The advice is wrong:

"<p>A smart meter can also show a ‘Live consumption’ feed which can be really helpful in identifying ‘vampiric’ sockets!</p>" 

By smart meter, we mean the ones the energy supplier installs.

 I think someone means devices with high standby, but actually, in community buildings these devices are rare and even in homes, this advice is 15 years out of date for almost every electrical item.  

Smart meter readings aren't live enough to use in this way (30 minute readings with a delay to the web.)   Clamp-on meters are, but  it's a nightmare trying to find where the high use is in a community building; requires two people, one at the display and one going around turning things on and off, and no other people in the building at the time.  

Modern advice would be to check the sleep/hibernate options on all devices that tend to stay awake all the time to receive software updates - smart TVs, computers - and unplug very old electrical devices when not in use.  We deemed this not important enough to get a card.

**Comment by JeanCarletta** [comment]
Suggested text:  


`<p>Twice hourly smart meter readings will help the UK reduce the number of power stations we need. Smart meters have a display you can put elsewhere to show how much energy you use. If the supplier won’t give you all the data, you can get it using a third party app.  The full data will allow you and your professionals to spot waste and estimate the cost of energy for room hires. </p><p>
Installers can test the meter will be able to connect to the network before installation.  The meters have improved greatly in the last few years.</p>`

**Comment by robwoodford** [comment]
Looks like you have updated this in the excel sheet, so closing this now.
