### ISSUE TITLE
move the raising finance cards.

### ISSUE THREAD

**Issue by JeanCarletta** [robwoodford/SEC-Card-Game-staging#14]
'get a grant’ card can be put in step 3 and the green tariffs with decarbonise step (4).

**Comment by JeanCarletta** [comment]
This change has a knock on effect for the tasks - there are no tasks that cover these cards in the petals for those steps at present.

**Comment by robwoodford** [comment]
Get a grant seems to match to Review funding database and green tariffs with the Buy Green Electricity. Therefore, this seems to be resolved
