### ISSUE TITLE
10 petals on side bar no longer there

### ISSUE THREAD

**Issue by robwoodford** [robwoodford/SEC-Card-Game-staging#2]
The ten petal high level categories are no longer on the left side bar.

Those ten petals should return. (as before). In addition, I recommend not having the tasks or cards on the side-bar (which from an UX perspective overwhelms and means it is not as easy for the user to navigate.)

**Comment by JeanCarletta** [comment]
We'll find you want to website refactored when we have the correct URL to divide off the game from the toolkit structure, but OK for now.
