### ISSUE TITLE
unreadable petal graphic

### ISSUE THREAD

**Issue by JeanCarletta** [robwoodford/SEC-Card-Game-staging#3]
change italics on petals to non-italics.

**Comment by JeanCarletta** [comment]
path is graphics/NetZeroActionPlan10petals.jpg

**Comment by robwoodford** [comment]
Thanks. I changed the graphic to a .png when I updated this. Does that matter it's in that format - is it linked elsewhere?

**Comment by JeanCarletta** [comment]
done.
