### ISSUE TITLE
cards too hidden

### ISSUE THREAD

**Issue by JeanCarletta** [robwoodford/SEC-Card-Game-staging#6]
suggested change just puts The Card Game at top level that shows the cards like all-cards does, with how to use the cards and how to read them underneath.

To decide to do this:

* copy junk/card-game.md to card-game.md (at top level)

* change the header of how_to_use_cards.md, reading-a-card.md, so parent is The Card Game.

* Delete wildcard.md

**Comment by JeanCarletta** [comment]
Ah, the issue webpage renders the markdown.  Intended new page can be found in junk/card-game.md so the suggested change is:

copy junk/card-game.md to card-game.md (at top level)

change the header of how_to_use_cards.md, reading-a-card.md, so parent is The Card Game.

Delete wildcard.md

**Comment by robwoodford** [comment]
I think the The Online Cards (now changed to Online Cards Edition) works well to bring this out, thanks.
